# Generated by Django 5.0.6 on 2024-06-24 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "blog_id",
                    models.AutoField(
                        db_column="blog_id", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=255)),
                ("title", models.TextField(db_column="title")),
                ("content", models.TextField(db_column="content")),
                (
                    "image",
                    models.ImageField(
                        blank=True, db_column="image", null=True, upload_to=""
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, db_column="datetime"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Blog",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "comment_id",
                    models.AutoField(
                        db_column="comment_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, db_column="datetime"),
                ),
                ("content", models.TextField(db_column="content")),
                (
                    "blog_id",
                    models.ForeignKey(
                        db_column="blog_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog_app.blog",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Comment",
            },
        ),
        migrations.CreateModel(
            name="Love",
            fields=[
                (
                    "love_id",
                    models.AutoField(
                        db_column="love_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, db_column="datetime"),
                ),
                (
                    "blog_id",
                    models.ForeignKey(
                        db_column="blog_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog_app.blog",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Love",
            },
        ),
    ]
