# Generated by Django 5.0.6 on 2024-06-25 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='blog_app.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blog'),
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_date',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user_id')},
        ),
        migrations.DeleteModel(
            name='Love',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
